# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# <span class='vtinteresting-url vtitem-HTTPS://GITHUB.COM/MICROSOFT/ACTION-PSSCRIPTANALYZER'>https://github.com/microsoft/action-psscriptanalyzer</span>
# For more information on PSScriptAnalyzer in general, see
# <span class='vtinteresting-url vtitem-HTTPS://GITHUB.COM/POWERSHELL/PSSCRIPTANALYZER'>https://github.com/PowerShell/PSScriptAnalyzer</span>

name: PSScriptAnalyzer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '19 18 * * 1'
    
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@<span class='vtinteresting-hash vtitem-2044AE068E37D0161FA2127DE04C19633882F061'>2044ae068e37d0161fa2127de04c19633882f061</span>
        with:
          # Check <span class='vtinteresting-url vtitem-HTTPS://GITHUB.COM/MICROSOFT/ACTION-PSSCRIPTANALYZER'>https://github.com/microsoft/action-psscriptanalyzer</span> for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          path: .\
          recurse: true 
          # Include your own basic security rules. Removing this option will run all the rules 
          includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText"'
          output: <span class='vtitem-discarded'>results.sarif</span>
      
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: <span class='vtitem-discarded'>results.sarif</span>
